spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    streams:
      application-id: "confluent-twitter-stream"
      replication-factor: "3"
      properties:
        security.protocol: "SASL_SSL"
        default.key.serde: "org.apache.kafka.common.serialization.Serdes$StringSerde"
        default.value.serde: "io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde"
        sasl.jaas.config: "sasl-jaas-config"
        sasl.mechanism: "PLAIN"
        schema.registry.url: "https://psrc-epkz2.ap-southeast-2.aws.confluent.cloud"
        basic.auth.user.info: "BASIC-AUTH-USER-INFO"
        basic.auth.credentials.source: "USER_INFO"

topic:
  name: "payments"
